### PR TITLE
[Feature] Add email notifications 

### PR DESCRIPTION
**Pull request by AyakorK**
### Description

Additions of a new feature of emails when : 
- We receive an answer to an initiative.
- A new blog related to an initiative has been created.

### Additions :

- Initiative Answer
    I. Sending of an email, extending of the command
    II. Extend our mailer to add the new function "notify_answer"
    III. Creation of new views for our mail
    IV. Additions of test for this feature
- New Blog creation
    I. Sending of an email, extending of the command
    II. Creation of a mailer to send the email with the function "notify_blog"
    III. Creation of multiple views to create an email following the format of the other ones.
    IV. Additions of test for this feature
- Common changes
    I. Addition of few locales

### How to test (most efficient way to test)

- Boot your platform
- Log in as a user
- Follow one of the initiatives
- Log out and log in as an admin
- Go to the initiative
- With your admin, answer to the initiative in the BackOffice
- Check if you received the mail in letter_opener
- Go back to your initiative on "Blog"
- Create a Blog in the BackOffice with your admin
- Check if you received the mail in letter_opener

### CODE REVIEW

**Review by luciegrau — APPROVED** [review]
Works great for me, thank you Guillaume !

**Comment by AyakorK** [comment]
It should be ok with the last commits @paulinebessoles

**Review by eliegaboriau — CHANGES_REQUESTED** [review]
Hello @AyakorK 
It should actually works without your PR : 
The events manager actually calls for notification and email when called.
The problem is probably in the notifications config, it should be in "real time".
Sorry for the useless work :(

**Comment by AyakorK** [comment]
After some checks, we saw that was a useless feature as it already exists but didn't work properly.

**Pull request closed without merging**
